# Generated by Django 4.0.4 on 2024-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.TextField(default='General', max_length=100),
        ),
    ]
