# Generated by Django 4.0.4 on 2024-06-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sponsor_alter_teammember_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sponsor',
            new_name='sponsorList',
        ),
    ]
